apiVersion: v1
kind: Pod
metadata:
  name: static-web
  labels:
    role: myrole
spec:
  containers:
    - name: web
      image: jpetrous/docker-demo
      ports:
        - name: web
          containerPort: 3000
          protocol: TCP